version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    rebase-strategy: "auto"
    versioning-strategy: "lockfile-only"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "12:00"
      timezone: "Asia/Baghdad"
    groups:
      dependencies:
        patterns:
          - "*"
