name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/CODEOWNERS
      - .github/dependabot.yml
      - .github/workflows/ci.yml
      - .github/workflows/release.yml

    pull_request:
      branches:
        - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run tests and generate coverage report
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-text

      - name: Check code coverage
        id: coverage_check
        run: |
          # Parse the coverage report
          coverage=$(vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-text)
          
          # Extract coverage percentages using grep and awk
          lines_coverage=$(echo "$coverage" | grep "Lines:" | awk '{print $2}' | sed 's/%//')
          functions_coverage=$(echo "$coverage" | grep "Functions:" | awk '{print $2}' | sed 's/%//')
          classes_coverage=$(echo "$coverage" | grep "Classes:" | awk '{print $2}' | sed 's/%//')
          branches_coverage=$(echo "$coverage" | grep "Branches:" | awk '{print $2}' | sed 's/%//')

          echo "Lines coverage: $lines_coverage%"
          echo "Functions coverage: $functions_coverage%"
          echo "Classes coverage: $classes_coverage%"
          echo "Branches coverage: $branches_coverage%"

#          # Check if any coverage metric is below the threshold
#          if [ "$lines_coverage" -lt 70 ] || [ "$functions_coverage" -lt 70 ] || [ "$classes_coverage" -lt 70 ] || [ "$branches_coverage" -lt 70 ]; then
#            echo "Coverage is below the threshold of 70%."
#            exit 1
#          else
#            echo "Coverage meets the minimum threshold."
#          fi
