name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "New version type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
          - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "mja.ise.1981@gmail.com"
          git config --global user.name "MJAISE"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Bump version
        id: bump_version
        run: |
          CURRENT_VERSION=$(jq -r '.version' composer.json)
          echo "Current version: $CURRENT_VERSION"
          VERSION_TYPE=${{ github.event.inputs.version_type }}

          IFS='.' read -r -a version_parts <<< "$CURRENT_VERSION"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}

          if [[ "$VERSION_TYPE" == "patch" ]]; then
            patch=$((patch + 1))
          elif [[ "$VERSION_TYPE" == "minor" ]]; then
            minor=$((minor + 1))
            patch=0
          elif [[ "$VERSION_TYPE" == "major" ]]; then
            major=$((major + 1))
            minor=0
            patch=0
          else
            echo "Unsupported version type specified."
            exit 1
          fi

          NEW_VERSION="$major.$minor.$patch"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "after applying $VERSION_TYPE" >> $GITHUB_STEP_SUMMARY
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_STEP_SUMMARY

      - name: Update composer.json
        run: |
          jq --arg version "$NEW_VERSION" '.version = $version' composer.json > tmp.json && mv tmp.json composer.json
          git add composer.json
          git commit -m "Bump version to ${{ env.NEW_VERSION }}"

      - name: Create Git tag
        run: |
          git tag v${{ env.NEW_VERSION }}

      - name: Push new Git commit and tag
        run: |
          git push origin main
          git push origin v${{ env.NEW_VERSION }}

      - name: Build
        run: composer install --no-dev --optimize-autoloader

      - name: Publish on Packagist
        env:
          COMPOSER_AUTH: |
            {
              "http-basic": {
                "packagist.org": {
                  "username": "${{ secrets.COMPOSER_USERNAME }}",
                  "password": "${{ secrets.PACKAGIST_TOKEN }}"
                }
              }
            }
        run: |
          echo "Pushing package version to Packagist..."
          # Packagist should automatically pick up new tags from your repository
          # So no specific command is needed here to publish
