name: Release
on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "New version type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
          - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --local --unset-all "http.https://github.com/.extraheader"
          git config --local --add "http.https://github.com/.extraheader" \
              "AUTHORIZATION: Basic $(base64 <<< ${{ secrets.FIB_PAT }}:)"
          git config --global user.email "${GITHUB_ACTOR:-ci-noreply}@github.com"
          git config --global user.name "${GITHUB_ACTOR:-GitHub Actions}"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Bump version
        if: ${{ github.event.inputs.version_type != 'dev' }}
        run: |
          CURRENT_VERSION=$(composer show -s | grep "versions" | head -n 1 | awk '{print $2}')
          echo "Current version: $CURRENT_VERSION"
          VERSION_TYPE=${{ github.event.inputs.version_type }}
          IFS='.' read -r -a version_parts <<< "$CURRENT_VERSION"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          if [[ "$VERSION_TYPE" == "patch" ]]; then
            patch=$((patch + 1))
          elif [[ "$VERSION_TYPE" == "minor" ]]; then
            minor=$((minor + 1))
            patch=0
          elif [[ "$VERSION_TYPE" == "major" ]]; then
            major=$((major + 1))
            minor=0
            patch=0
          else
            echo "Unsupported version type specified."
            exit 1
          fi
          NEW_VERSION="$major.$minor.$patch"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "Computed new version: $NEW_VERSION"

      - name: Debug NEW_VERSION
        run: echo "NEW_VERSION is ${{ env.NEW_VERSION }}"

      - name: Update composer.json
        if: ${{ github.event.inputs.version_type != 'dev' }}
        run: |
          composer config version ${{ env.NEW_VERSION }}
          git add composer.json
          git add composer.lock
          git commit -m "Bump version to ${{ env.NEW_VERSION }}"

      - name: Create Git tag
        if: ${{ github.event.inputs.version_type != 'dev' }}
        run: |
          git tag v${{ env.NEW_VERSION }}

      - name: Build
        if: ${{ github.event.inputs.version_type != 'dev' }}
        run: composer install --no-dev --optimize-autoloader

      - name: Publish on Packagist
        if: ${{ github.event.inputs.version_type != 'dev' }}
        env:
          COMPOSER_AUTH: '{"http-basic":{"composer.example.com":{"username":"${{ secrets.COMPOSER_USERNAME }}","password":"${{ secrets.COMPOSER_PASSWORD }}"}}}'
        run: |
          VERSION_TYPE=${{ github.event.inputs.version_type }}
          if [[ "$VERSION_TYPE" == "dev" ]]; then
            composer publish --access public --no-interaction --stability dev
          else
            composer publish --access public --no-interaction
          fi

      - name: Push new Git commit and tag
        if: ${{ github.event.inputs.version_type != 'dev' }}
        run: |
          git push origin main
          git push origin v${{ env.NEW_VERSION }}
